blank_issues_enabled: false
contact_links:
  - name: DevJobs Discussion / Discusión
    url: https://github.com/ipproyectosysoluciones/DevJobs/discussions
    about: Preguntas generales, ideas, o dudas / General questions, ideas, or doubts
