#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Validate commit message format
# Validar formato del mensaje de commit
# conventional commit format: type(scope): description
npx --no -- commitlint --edit $1